# https://github.com/hvr/multi-ghc-travis/blob/master/.travis.yml
language: c

env:
 - CABALVER=2.0 GHCVER=8.2.2
 - CABALVER=2.0 GHCVER=8.4.2
 - CABALVER=2.2 GHCVER=8.6.1
 - CABALVER=3.0 GHCVER=8.8.1 NEW_CABAL=1 PREFIX=new-

before_install:
 - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
 - travis_retry sudo apt-get update
 - travis_retry sudo apt-get install --force-yes cabal-install-$CABALVER ghc-$GHCVER
 - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH

install:
 - cabal --version
 - echo "$(ghc --version)"
 - travis_retry cabal update
 - if [ $NEW_CABAL ]; then cabal new-configure --enable-tests; cabal new-build --dependencies-only; else cabal install --only-dependencies --enable-tests; cabal configure --enable-tests; fi

script:
 - cabal ${PREFIX}build
 - cabal ${PREFIX}test
 - cabal ${PREFIX}sdist
